### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by cjsmeele** [UtrechtUniversity/yoda-portal#3]
We need a favicon!

**Comment by tsmeele** [comment]
Haha ontwerp er maar eentje, heben we inderdaad nog nodig.

Met vriendelijke groet,

Ton

Op 27 jul. 2015 om 16:21 heeft Chris Smeele <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


We need a favicon!

**Comment by cpavanrun** [comment]
Had a few moments. It's the D from data-based on an earlier YODA reference I saw. Should be house-style correct (color wise).

![yoda](https://cloud.githubusercontent.com/assets/9033494/25531810/405a684e-2c2b-11e7-90a6-6cb39149c1cb.png)


[yoda-ico.zip](https://github.com/UtrechtUniversity/yoda-portal/files/964509/yoda-ico.zip)

**Comment by cjsmeele** [comment]
That looks nice, thank you!

@pfrederiks could you add this one into the repo? According to Ton this can be merged into `release-0.9.6`.

**Comment by lwesterhof** [comment]
Fixed in 282eb21d6adf2885e3f8b9a9be8bdc94c521dda8.
