### ISSUE TITLE
Make $module module config accessible to modules

### ISSUE THREAD

**Issue by cjsmeele** [UtrechtUniversity/yoda-portal#4]
... by changing the name of the variable, or by moving the module library from [UtrechtUniversity/yoda-portal-ilab-intake](https://github.com/UtrechtUniversity/yoda-portal-ilab-intake) to this repo.

This will resolve the possibility of `$module['name']` becoming out of sync with a controller-set `$activeModule` variable, as is currently the case for the group manager.

(this applies to branch feature/dynamic-menu-generation)

**Comment by AJdeMooij** [comment]
Fixed in d33c5bcf2252dcc38190e98f537273b7c9261aa6
