### ISSUE TITLE
Coding style adjustments

### ISSUE THREAD

**Issue by cjsmeele** [UtrechtUniversity/yoda-portal#5]
Some of the code added to feature/dynamic-menu-generation does not follow the existing coding conventions in use for the rest of the portal.

e.g.: https://github.com/UtrechtUniversity/yoda-portal/blob/feature/dynamic-menu-generation/views/common-start.php#L92

For reference: Class names use PascalCase, methods and variables use camelCase.

**Comment by AJdeMooij** [comment]
Fixed in f2a7685ce3dbe804308b0965c8027e7e332cbea2
