### ISSUE TITLE
Filter module label in home view

### ISSUE THREAD

**Issue by cjsmeele** [UtrechtUniversity/yoda-portal#6]
(both in master and in feature/dynamic-menu-generation)

Module labels are not `htmlentities()`-ified in the module list. This will cause issues when developers or admins choose to have ampersands or angle brackets in their module labels.

**Comment by AJdeMooij** [comment]
Could only find one occurance of this in feature/dynamic-menu-generation, namely in views/home_index.php.

This was already htmlentitied within the menu. Tested with ampersands and angle brackets, but worked fine both with and without htmlentities
