### ISSUE TITLE
Yoda installation

### ISSUE THREAD

**Issue by felipegutierrez** [UtrechtUniversity/yoda-portal#8]
Hello dear developer,

Sorry for the simple question. How do I install Yoda on my Linux server? Because I didn't find any documentation about that.

Best Regards,
Felipe

**Comment by tsmeele** [comment]
Hello Felipe,
Currently the initial installation can be tedious. We plan to create an Ansible based installation procedure.

Current steps are:
- install Yoda portal (clone repo) and make its public subdir accessible as document root
- use Yoda Portal's ./tools/add-module.sh script to install relevant portal modules e.g. groupmanager
- install PRODS and Codeigniter repos in the same directory as Yoda portal
-  install the sudo microservices rpm
- clone irods-ruleset-uu into /etc/irods, cd into the subdir and run "make install".    Add the ruleset to the irods server rulesets.   
- NB: this should be sufficient for Yoda portal and groupmanager module.  Other modules may require a related ruleset
 
-

**Comment by felipegutierrez** [comment]
Hi Ton,

when I try to add a module as described at [here](https://github.com/UtrechtUniversity/yoda-portal/blob/master/docs/How%20to%20Add%20a%20Module.md#adding-the-module) I got a request for user from github. I tried with my user but I think it must be in the yoda group.
```
./tools/add-module.sh https://github.com/user/yoda-portal-module.git groupmanager
Cloning into 'groupmanager'...
Username for 'https://github.com': felipegutierrez
Password for 'https://felipegutierrez@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/user/yoda-portal-module.git/' not found
```

**Comment by tsmeele** [comment]
Hi Felipe,

Each Yoda module is located in a separate Github repository so to install the groupmanager use:

> ./tools/add-module.sh https://github.com/UtrechtUniversity/yoda-portal-group-manager.git groupmanager

BTW this will not ask for a username/password anymore.

**Comment by felipegutierrez** [comment]
thanks for reply Ton,

How do I install [sudo microservices](https://github.com/UtrechtUniversity/irods-sudo-microservices)? Do I have to compile them? and copy the *.so files to `https://github.com/UtrechtUniversity/irods-sudo-microservices`?

**Comment by felipegutierrez** [comment]
Hi @tsmeele , I got to install irods-sudo-microservice. thanks for the rpm file.
The PRODS and the Codeigniter I cloned and copy to the directory `/usr/local/` because yoda-portal is also in this directory. Is this right?
The irods-ruleset-uu I got to compile and configured the `server_config.json` like this:
```
"re_rulebase_set": [
        {
            "filename": "metadata_acPostProcForPut"
        },
        {
            "filename": "rules-uu"
        },
        {
            "filename": "core"
        }
    ],
```
I think this step is right.

The last thing I don't know how to figure out is very simple. I don't know what is the url of yoda portal. It uses Apache HTTPD server?

**Comment by tsmeele** [comment]
Hi Felipe,

If your httpd document root is /var/www/html that copy PRODS, Codeigniter and Yoda portal to that directory.
Then create a softlink called "public" in /var/www/html that points to the public subdir in yoda portal
Next, change the httpd document root to be /var/www/html/public

Also in Yoda portal you will find a template .htaccess that should be activitated in the /var/www/html/public directory.

Kind regards,

Ton

**Comment by felipegutierrez** [comment]
Hi @tsmeele , thanks for reply.
I am not sure if I configured every thing correctly. First I copied all apps to the `/var/www/html` dir, created the soft link and enabled the .htaccess file. Please, could you check below if I did every thing right?
```
yum install httpd php
cd /etc/httpd/conf.d/
mv ssl.conf ssl.conf.old

git clone https://github.com/DICE-UNC/irods-php.git
cp -Rf irods-php/ /var/www/html/

git clone https://github.com/UtrechtUniversity/CodeIgniter.git
cp -Rf CodeIgniter/ /var/www/html/

/var/www/html
ln -s yoda-portal/public/ public
ls -l
total 4
drwxr-xr-x  6 root root  134 Mar 23 10:44 CodeIgniter
drwxr-xr-x  5 root root  122 Mar 23 10:48 irods-php
lrwxrwxrwx  1 root root   19 Mar 24 06:06 public -> yoda-portal/public/
drwxr-xr-x 16 root root 4096 Mar  7 04:44 yoda-portal
```
File `/etc/httpd/conf/httpd.conf`.
```
DocumentRoot "/var/www/html/public"
<Directory "/var/www/html">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
```
and also restarted my Httpd server `service httpd restart`.
Now, when I access my address http://145.117.144.230/yoda-portal/index.php it says Not Found.  When I access http://145.117.144.230/ it shows the CodeIgniter index page. But only show if I put Davrods down on my server. If Davrods is up the Yoda URL tries to find a file into Davrods. I think they are in conflict.

**Comment by tsmeele** [comment]
Yes for now (test) keep davrods down, you will need to configure http vitual hosts to service both the portal and davrods from the same server. See Apache configuration guidelines for that scenario.

Config looks okay except that all is owned by root you may want to change that later.  Check the Apache http logs there might be other errors.

Kind regards,

Ton
